-- Rename Spanish enum values to English. RENAME VALUE preserves existing rows
-- (a row storing 'EN_CURSO' becomes 'IN_PROGRESS' automatically, no data loss).

ALTER TYPE "ExamCategory" RENAME VALUE 'ECOGRAFIA' TO 'ULTRASOUND';
ALTER TYPE "ExamCategory" RENAME VALUE 'LABORATORIO' TO 'LAB';

ALTER TYPE "AppointmentStatus" RENAME VALUE 'PENDIENTE' TO 'PENDING';
ALTER TYPE "AppointmentStatus" RENAME VALUE 'EN_CURSO' TO 'IN_PROGRESS';
ALTER TYPE "AppointmentStatus" RENAME VALUE 'REALIZADO' TO 'COMPLETED';
ALTER TYPE "AppointmentStatus" RENAME VALUE 'CANCELADO' TO 'CANCELLED';

ALTER TYPE "DiaryMood" RENAME VALUE 'GENIAL' TO 'GREAT';
ALTER TYPE "DiaryMood" RENAME VALUE 'BIEN' TO 'GOOD';
ALTER TYPE "DiaryMood" RENAME VALUE 'NORMAL' TO 'OKAY';
ALTER TYPE "DiaryMood" RENAME VALUE 'CANSADA' TO 'TIRED';
ALTER TYPE "DiaryMood" RENAME VALUE 'MAL' TO 'BAD';

ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'PENDING';
